name: ${project.parent.name}
version: ${project.parent.version}
main: ${project.groupId}.minecraftmarket.${project.artifactId}.MCMarket
softdepend: [Multiverse-Core, MultiWorld]
authors: [R4G3_BABY]
description: ${project.parent.description}
website: ${project.parent.url}

commands:
  MinecraftMarket:
    permission: minecraftmarket.use
    description: Manage plugin functionalities
    aliases: [mm]
    usage: /<command> <args>
  MMGui:
    description: Open MinecraftMarket GUI
    usage: /<command>

permissions:
  minecraftmarket.use:
    description: Allows main command usage
    default: op
  minecraftmarket.signs:
    description: Can break signs to remove them
    default: op